# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/project/MyProject/Link

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/project/MyProject/Link

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/project/MyProject/Link/CMakeFiles /root/project/MyProject/Link/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/project/MyProject/Link/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named link

# Build rule for target.
link: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 link
.PHONY : link

# fast build rule for target.
link/fast:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/build
.PHONY : link/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

link/base/CThread.o: link/base/CThread.cc.o

.PHONY : link/base/CThread.o

# target to build an object file
link/base/CThread.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/base/CThread.cc.o
.PHONY : link/base/CThread.cc.o

link/base/CThread.i: link/base/CThread.cc.i

.PHONY : link/base/CThread.i

# target to preprocess a source file
link/base/CThread.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/base/CThread.cc.i
.PHONY : link/base/CThread.cc.i

link/base/CThread.s: link/base/CThread.cc.s

.PHONY : link/base/CThread.s

# target to generate assembly for a file
link/base/CThread.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/base/CThread.cc.s
.PHONY : link/base/CThread.cc.s

link/base/Thread.o: link/base/Thread.cc.o

.PHONY : link/base/Thread.o

# target to build an object file
link/base/Thread.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/base/Thread.cc.o
.PHONY : link/base/Thread.cc.o

link/base/Thread.i: link/base/Thread.cc.i

.PHONY : link/base/Thread.i

# target to preprocess a source file
link/base/Thread.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/base/Thread.cc.i
.PHONY : link/base/Thread.cc.i

link/base/Thread.s: link/base/Thread.cc.s

.PHONY : link/base/Thread.s

# target to generate assembly for a file
link/base/Thread.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/base/Thread.cc.s
.PHONY : link/base/Thread.cc.s

link/net/Buffer.o: link/net/Buffer.cc.o

.PHONY : link/net/Buffer.o

# target to build an object file
link/net/Buffer.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/Buffer.cc.o
.PHONY : link/net/Buffer.cc.o

link/net/Buffer.i: link/net/Buffer.cc.i

.PHONY : link/net/Buffer.i

# target to preprocess a source file
link/net/Buffer.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/Buffer.cc.i
.PHONY : link/net/Buffer.cc.i

link/net/Buffer.s: link/net/Buffer.cc.s

.PHONY : link/net/Buffer.s

# target to generate assembly for a file
link/net/Buffer.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/Buffer.cc.s
.PHONY : link/net/Buffer.cc.s

link/net/EventLoop.o: link/net/EventLoop.cc.o

.PHONY : link/net/EventLoop.o

# target to build an object file
link/net/EventLoop.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoop.cc.o
.PHONY : link/net/EventLoop.cc.o

link/net/EventLoop.i: link/net/EventLoop.cc.i

.PHONY : link/net/EventLoop.i

# target to preprocess a source file
link/net/EventLoop.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoop.cc.i
.PHONY : link/net/EventLoop.cc.i

link/net/EventLoop.s: link/net/EventLoop.cc.s

.PHONY : link/net/EventLoop.s

# target to generate assembly for a file
link/net/EventLoop.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoop.cc.s
.PHONY : link/net/EventLoop.cc.s

link/net/EventLoopThread.o: link/net/EventLoopThread.cc.o

.PHONY : link/net/EventLoopThread.o

# target to build an object file
link/net/EventLoopThread.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoopThread.cc.o
.PHONY : link/net/EventLoopThread.cc.o

link/net/EventLoopThread.i: link/net/EventLoopThread.cc.i

.PHONY : link/net/EventLoopThread.i

# target to preprocess a source file
link/net/EventLoopThread.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoopThread.cc.i
.PHONY : link/net/EventLoopThread.cc.i

link/net/EventLoopThread.s: link/net/EventLoopThread.cc.s

.PHONY : link/net/EventLoopThread.s

# target to generate assembly for a file
link/net/EventLoopThread.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoopThread.cc.s
.PHONY : link/net/EventLoopThread.cc.s

link/net/EventLoopThreadPool.o: link/net/EventLoopThreadPool.cc.o

.PHONY : link/net/EventLoopThreadPool.o

# target to build an object file
link/net/EventLoopThreadPool.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoopThreadPool.cc.o
.PHONY : link/net/EventLoopThreadPool.cc.o

link/net/EventLoopThreadPool.i: link/net/EventLoopThreadPool.cc.i

.PHONY : link/net/EventLoopThreadPool.i

# target to preprocess a source file
link/net/EventLoopThreadPool.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoopThreadPool.cc.i
.PHONY : link/net/EventLoopThreadPool.cc.i

link/net/EventLoopThreadPool.s: link/net/EventLoopThreadPool.cc.s

.PHONY : link/net/EventLoopThreadPool.s

# target to generate assembly for a file
link/net/EventLoopThreadPool.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/EventLoopThreadPool.cc.s
.PHONY : link/net/EventLoopThreadPool.cc.s

link/net/IOEvent.o: link/net/IOEvent.cc.o

.PHONY : link/net/IOEvent.o

# target to build an object file
link/net/IOEvent.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOEvent.cc.o
.PHONY : link/net/IOEvent.cc.o

link/net/IOEvent.i: link/net/IOEvent.cc.i

.PHONY : link/net/IOEvent.i

# target to preprocess a source file
link/net/IOEvent.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOEvent.cc.i
.PHONY : link/net/IOEvent.cc.i

link/net/IOEvent.s: link/net/IOEvent.cc.s

.PHONY : link/net/IOEvent.s

# target to generate assembly for a file
link/net/IOEvent.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOEvent.cc.s
.PHONY : link/net/IOEvent.cc.s

link/net/IOEventCtrl.o: link/net/IOEventCtrl.cc.o

.PHONY : link/net/IOEventCtrl.o

# target to build an object file
link/net/IOEventCtrl.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOEventCtrl.cc.o
.PHONY : link/net/IOEventCtrl.cc.o

link/net/IOEventCtrl.i: link/net/IOEventCtrl.cc.i

.PHONY : link/net/IOEventCtrl.i

# target to preprocess a source file
link/net/IOEventCtrl.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOEventCtrl.cc.i
.PHONY : link/net/IOEventCtrl.cc.i

link/net/IOEventCtrl.s: link/net/IOEventCtrl.cc.s

.PHONY : link/net/IOEventCtrl.s

# target to generate assembly for a file
link/net/IOEventCtrl.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOEventCtrl.cc.s
.PHONY : link/net/IOEventCtrl.cc.s

link/net/IOMultiplex.o: link/net/IOMultiplex.cc.o

.PHONY : link/net/IOMultiplex.o

# target to build an object file
link/net/IOMultiplex.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOMultiplex.cc.o
.PHONY : link/net/IOMultiplex.cc.o

link/net/IOMultiplex.i: link/net/IOMultiplex.cc.i

.PHONY : link/net/IOMultiplex.i

# target to preprocess a source file
link/net/IOMultiplex.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOMultiplex.cc.i
.PHONY : link/net/IOMultiplex.cc.i

link/net/IOMultiplex.s: link/net/IOMultiplex.cc.s

.PHONY : link/net/IOMultiplex.s

# target to generate assembly for a file
link/net/IOMultiplex.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/IOMultiplex.cc.s
.PHONY : link/net/IOMultiplex.cc.s

link/net/Socket.o: link/net/Socket.cc.o

.PHONY : link/net/Socket.o

# target to build an object file
link/net/Socket.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/Socket.cc.o
.PHONY : link/net/Socket.cc.o

link/net/Socket.i: link/net/Socket.cc.i

.PHONY : link/net/Socket.i

# target to preprocess a source file
link/net/Socket.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/Socket.cc.i
.PHONY : link/net/Socket.cc.i

link/net/Socket.s: link/net/Socket.cc.s

.PHONY : link/net/Socket.s

# target to generate assembly for a file
link/net/Socket.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/Socket.cc.s
.PHONY : link/net/Socket.cc.s

link/net/SocketAddr.o: link/net/SocketAddr.cc.o

.PHONY : link/net/SocketAddr.o

# target to build an object file
link/net/SocketAddr.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/SocketAddr.cc.o
.PHONY : link/net/SocketAddr.cc.o

link/net/SocketAddr.i: link/net/SocketAddr.cc.i

.PHONY : link/net/SocketAddr.i

# target to preprocess a source file
link/net/SocketAddr.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/SocketAddr.cc.i
.PHONY : link/net/SocketAddr.cc.i

link/net/SocketAddr.s: link/net/SocketAddr.cc.s

.PHONY : link/net/SocketAddr.s

# target to generate assembly for a file
link/net/SocketAddr.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/SocketAddr.cc.s
.PHONY : link/net/SocketAddr.cc.s

link/net/SocketOperation.o: link/net/SocketOperation.cc.o

.PHONY : link/net/SocketOperation.o

# target to build an object file
link/net/SocketOperation.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/SocketOperation.cc.o
.PHONY : link/net/SocketOperation.cc.o

link/net/SocketOperation.i: link/net/SocketOperation.cc.i

.PHONY : link/net/SocketOperation.i

# target to preprocess a source file
link/net/SocketOperation.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/SocketOperation.cc.i
.PHONY : link/net/SocketOperation.cc.i

link/net/SocketOperation.s: link/net/SocketOperation.cc.s

.PHONY : link/net/SocketOperation.s

# target to generate assembly for a file
link/net/SocketOperation.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/SocketOperation.cc.s
.PHONY : link/net/SocketOperation.cc.s

link/net/TcpAccept.o: link/net/TcpAccept.cc.o

.PHONY : link/net/TcpAccept.o

# target to build an object file
link/net/TcpAccept.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpAccept.cc.o
.PHONY : link/net/TcpAccept.cc.o

link/net/TcpAccept.i: link/net/TcpAccept.cc.i

.PHONY : link/net/TcpAccept.i

# target to preprocess a source file
link/net/TcpAccept.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpAccept.cc.i
.PHONY : link/net/TcpAccept.cc.i

link/net/TcpAccept.s: link/net/TcpAccept.cc.s

.PHONY : link/net/TcpAccept.s

# target to generate assembly for a file
link/net/TcpAccept.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpAccept.cc.s
.PHONY : link/net/TcpAccept.cc.s

link/net/TcpConnect.o: link/net/TcpConnect.cc.o

.PHONY : link/net/TcpConnect.o

# target to build an object file
link/net/TcpConnect.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpConnect.cc.o
.PHONY : link/net/TcpConnect.cc.o

link/net/TcpConnect.i: link/net/TcpConnect.cc.i

.PHONY : link/net/TcpConnect.i

# target to preprocess a source file
link/net/TcpConnect.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpConnect.cc.i
.PHONY : link/net/TcpConnect.cc.i

link/net/TcpConnect.s: link/net/TcpConnect.cc.s

.PHONY : link/net/TcpConnect.s

# target to generate assembly for a file
link/net/TcpConnect.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpConnect.cc.s
.PHONY : link/net/TcpConnect.cc.s

link/net/TcpServer.o: link/net/TcpServer.cc.o

.PHONY : link/net/TcpServer.o

# target to build an object file
link/net/TcpServer.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpServer.cc.o
.PHONY : link/net/TcpServer.cc.o

link/net/TcpServer.i: link/net/TcpServer.cc.i

.PHONY : link/net/TcpServer.i

# target to preprocess a source file
link/net/TcpServer.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpServer.cc.i
.PHONY : link/net/TcpServer.cc.i

link/net/TcpServer.s: link/net/TcpServer.cc.s

.PHONY : link/net/TcpServer.s

# target to generate assembly for a file
link/net/TcpServer.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/TcpServer.cc.s
.PHONY : link/net/TcpServer.cc.s

link/net/echo.o: link/net/echo.cc.o

.PHONY : link/net/echo.o

# target to build an object file
link/net/echo.cc.o:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/echo.cc.o
.PHONY : link/net/echo.cc.o

link/net/echo.i: link/net/echo.cc.i

.PHONY : link/net/echo.i

# target to preprocess a source file
link/net/echo.cc.i:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/echo.cc.i
.PHONY : link/net/echo.cc.i

link/net/echo.s: link/net/echo.cc.s

.PHONY : link/net/echo.s

# target to generate assembly for a file
link/net/echo.cc.s:
	$(MAKE) -f CMakeFiles/link.dir/build.make CMakeFiles/link.dir/link/net/echo.cc.s
.PHONY : link/net/echo.cc.s

test/test.o: test/test.cc.o

.PHONY : test/test.o

# target to build an object file
test/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cc.o
.PHONY : test/test.cc.o

test/test.i: test/test.cc.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cc.i
.PHONY : test/test.cc.i

test/test.s: test/test.cc.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cc.s
.PHONY : test/test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... link"
	@echo "... test"
	@echo "... link/base/CThread.o"
	@echo "... link/base/CThread.i"
	@echo "... link/base/CThread.s"
	@echo "... link/base/Thread.o"
	@echo "... link/base/Thread.i"
	@echo "... link/base/Thread.s"
	@echo "... link/net/Buffer.o"
	@echo "... link/net/Buffer.i"
	@echo "... link/net/Buffer.s"
	@echo "... link/net/EventLoop.o"
	@echo "... link/net/EventLoop.i"
	@echo "... link/net/EventLoop.s"
	@echo "... link/net/EventLoopThread.o"
	@echo "... link/net/EventLoopThread.i"
	@echo "... link/net/EventLoopThread.s"
	@echo "... link/net/EventLoopThreadPool.o"
	@echo "... link/net/EventLoopThreadPool.i"
	@echo "... link/net/EventLoopThreadPool.s"
	@echo "... link/net/IOEvent.o"
	@echo "... link/net/IOEvent.i"
	@echo "... link/net/IOEvent.s"
	@echo "... link/net/IOEventCtrl.o"
	@echo "... link/net/IOEventCtrl.i"
	@echo "... link/net/IOEventCtrl.s"
	@echo "... link/net/IOMultiplex.o"
	@echo "... link/net/IOMultiplex.i"
	@echo "... link/net/IOMultiplex.s"
	@echo "... link/net/Socket.o"
	@echo "... link/net/Socket.i"
	@echo "... link/net/Socket.s"
	@echo "... link/net/SocketAddr.o"
	@echo "... link/net/SocketAddr.i"
	@echo "... link/net/SocketAddr.s"
	@echo "... link/net/SocketOperation.o"
	@echo "... link/net/SocketOperation.i"
	@echo "... link/net/SocketOperation.s"
	@echo "... link/net/TcpAccept.o"
	@echo "... link/net/TcpAccept.i"
	@echo "... link/net/TcpAccept.s"
	@echo "... link/net/TcpConnect.o"
	@echo "... link/net/TcpConnect.i"
	@echo "... link/net/TcpConnect.s"
	@echo "... link/net/TcpServer.o"
	@echo "... link/net/TcpServer.i"
	@echo "... link/net/TcpServer.s"
	@echo "... link/net/echo.o"
	@echo "... link/net/echo.i"
	@echo "... link/net/echo.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

